### ISSUE TITLE
Strptime Undefined Reference Error

### ISSUE THREAD

**Issue by dcdenu4** [wavebitscientific/datetime-fortran#63]
I get the following error when trying to use the `strptime` function:

    .\obj\test_strptime.o:test_strptime.f90:(.text.startup+0x5d): undefined reference to `__mod_datetime_MOD_strptime'
    .\obj\test_strptime.o:test_strptime.f90:(.text.startup+0xdf): undefined reference to `__mod_datetime_MOD_strptime'
    collect2.exe: error: ld returned 1 exit status

I'm trying to use the public `strptime` function like follows:

```
program teststrptime

use datetime_module

type(datetime)  :: date1,date2
type(timedelta) :: timediff

! Example times in "YYYYMMDD hhmmss" format
character(len=15) :: str1 = "20130512 091519"
character(len=15) :: str2 = "20131116 120418"

date1 = strptime(str1,"%Y%m%d %H%M%S")
date2 = strptime(str2,"%Y%m%d %H%M%S")

timediff = date2-date1

!write(*,*)timediff
!write(*,*)timediff%total_seconds()

end program teststrptime
```

I am using gfortran GCC 6.3.0 from MinGW on Windows. I have the datetime-fortran library in a *lib* folder and the mod files in a *include* folder. I'm compiling like so:

    gfortran -O2 -fbacktrace -c test_strptime.f90 -o .\obj\test_strptime.o -L./lib -ldatetime -I./include/ -I./obj -J./obj
    gfortran -O2 -fbacktrace -o teststrptime .\obj\test_strptime.o

Using `date2num` instead of using `strptime` does not cause an error during compiling.

Any suggestions would be appreciated. I'm still fairly new at linking libraries for Fortran development.

**Comment by milancurcic** [comment]
Hi Doug,

Not sure what's going on here. I can compile and link the example without issues on my system (Ubuntu). 

This is a linker error so your compile step works. It seems like you have a libdatetime.a (otherwise the linker would complain about it) but it can't find the strptime method in there. Just for a sanity check, what is the output of `nm libdatetime.a | grep __mod_datetime_MOD_strptime` for you? You should get something like `0000000000000346 T __mod_datetime_MOD_strptime` is libdatetime.a was created correctly.

Unfortunately I have zero experience with MinGW, so I don't know if this could be related to it.

**Comment by dcdenu4** [comment]
Hey, thanks for the quick reply. Running the sanity command check you mentioned gives:

    0000000000002290 T __mod_datetime_MOD_strptime

I think the issue is related to using WSL to build / compile datetime-fortran, but then switching back over to using MinGW to link the library to my project. Unfortunately we're using MinGW and Windows across the project.

**Comment by VinniDoddu** [comment]
Hi,
is there an easy solution to get datetime-fortran working using mingw in windows ?
thanks

**Comment by milancurcic** [comment]
Hi @VinniDoddu,

Unfortunately, I haven't learned anything new since the start of this issue, and still have zero experience with MinGW. From reviewing the issue again, my suspicion is that on MinGW the linker is not able to find `strptime`. This should be in the C standard library inside `time.h`. I don't know if on MinGW this function is not provided, or perhaps defined in some other place that is not in default include and link path.

**Comment by milancurcic** [comment]
@scivision just added a fix for this which is now in master.

@dcdenu4 @VinniDoddu Can you try it and see if it works?

**Comment by milancurcic** [comment]
Closing. If the issue persists, please reopen.

**Comment by dcdenu4** [comment]
> @scivision just added a fix for this which is now in master.
> 
> @dcdenu4 VinniDoddu Can you try it and see if it works?

Hey, sorry I missed this. I'm no longer on the project that pertained to this issue and don't have access to the codebase... Thanks for the work and reaching out!
